require "media/persistence"
require_relative "../lib/media/resource"

module Media
  Persistence::DB.transaction do

    [
      [100, "Business"],
      [101, "Engineering"],
      [102, "Art & Architecture"],
      [103, "Health & Medicine"],
      [104, "History"],
      [106, "Language"],
      [107, "Literature"],
      [108, "Mathematics"],
      [109, "Science"],
      [110, "Psychology & Social Science"],
      [111, "Society"],
      [112, "Teaching & Learning"],
      [113, "Communications & Media"],
      [114, "Philosophy"],
      [115, "Religion & Spirituality"],
      [116, "Law & Politics"],
    ].each do |(code, name)|
      Resource::Models::Category.find_or_create(code: code, name: name)
    end

    [
      ["aa", "Afar"],
      ["ab", "Abkhazian"],
      ["af", "Afrikaans"],
      ["ak", "Akan"],
      ["sq", "Albanian"],
      ["am", "Amharic"],
      ["ar", "Arabic"],
      ["an", "Aragonese"],
      ["hy", "Armenian"],
      ["as", "Assamese"],
      ["av", "Avaric"],
      ["ae", "Avestan"],
      ["ay", "Aymara"],
      ["az", "Azerbaijani"],
      ["ba", "Bashkir"],
      ["bm", "Bambara"],
      ["eu", "Basque"],
      ["be", "Belarusian"],
      ["bn", "Bengali"],
      ["bh", "Bihari"],
      ["bi", "Bislama"],
      ["bs", "Bosnian"],
      ["br", "Breton"],
      ["bg", "Bulgarian"],
      ["my", "Burmese"],
      ["ca", "Catalan"],
      ["ch", "Chamorro"],
      ["ce", "Chechen"],
      ["zh", "Chinese"],
      ["cu", "Church Slavic"],
      ["cv", "Chuvash"],
      ["kw", "Cornish"],
      ["co", "Corsican"],
      ["cr", "Cree"],
      ["cs", "Czech"],
      ["da", "Danish"],
      ["dv", "Divehi"],
      ["nl", "Dutch"],
      ["dz", "Dzongkha"],
      ["en", "English"],
      ["eo", "Esperanto"],
      ["et", "Estonian"],
      ["ee", "Ewe"],
      ["fo", "Faroese"],
      ["fj", "Fijian"],
      ["fi", "Finnish"],
      ["fr", "French"],
      ["fy", "WesternFrisian"],
      ["ff", "Fulah"],
      ["ka", "Georgian"],
      ["de", "German"],
      ["gd", "Gaelic"],
      ["ga", "Irish"],
      ["gl", "Galician"],
      ["gv", "Manx"],
      ["el", "Greek"],
      ["gn", "Guarani"],
      ["gu", "Gujarati"],
      ["ht", "Haitian"],
      ["ha", "Hausa"],
      ["he", "Hebrew"],
      ["hz", "Herero"],
      ["hi", "Hindi"],
      ["ho", "HiriMotu"],
      ["hr", "Croatian"],
      ["hu", "Hungarian"],
      ["ig", "Igbo"],
      ["is", "Icelandic"],
      ["io", "Ido"],
      ["ii", "SichuanYi"],
      ["iu", "Inuktitut"],
      ["ie", "Interlingue"],
      ["ia", "Interlingua"],
      ["id", "Indonesian"],
      ["ik", "Inupiaq"],
      ["it", "Italian"],
      ["jv", "Javanese"],
      ["ja", "Japanese"],
      ["kl", "Kalaallisut"],
      ["kn", "Kannada"],
      ["ks", "Kashmiri"],
      ["kr", "Kanuri"],
      ["kk", "Kazakh"],
      ["km", "CentralKhmer"],
      ["ki", "Kikuyu"],
      ["rw", "Kinyarwanda"],
      ["ky", "Kirghiz"],
      ["kv", "Komi"],
      ["kg", "Kongo"],
      ["ko", "Korean"],
      ["kj", "Kuanyama"],
      ["ku", "Kurdish"],
      ["lo", "Lao"],
      ["la", "Latin"],
      ["lv", "Latvian"],
      ["li", "Limburgan"],
      ["ln", "Lingala"],
      ["lt", "Lithuanian"],
      ["lb", "Luxembourgish"],
      ["lu", "Luba-Katanga"],
      ["lg", "Ganda"],
      ["mk", "Macedonian"],
      ["mh", "Marshallese"],
      ["ml", "Malayalam"],
      ["mi", "Maori"],
      ["mr", "Marathi"],
      ["ms", "Malay"],
      ["mg", "Malagasy"],
      ["mt", "Maltese"],
      ["mn", "Mongolian"],
      ["na", "Nauru"],
      ["nv", "Navajo"],
      ["nr", "Ndebele"],
      ["nd", "Ndebele"],
      ["ng", "Ndonga"],
      ["ne", "Nepali"],
      ["nn", "NorwegianNynorsk"],
      ["nb", "Bokmål"],
      ["no", "Norwegian"],
      ["ny", "Chichewa"],
      ["oc", "Occitan"],
      ["oj", "Ojibwa"],
      ["or", "Oriya"],
      ["om", "Oromo"],
      ["os", "Ossetian"],
      ["pa", "Panjabi"],
      ["fa", "Persian"],
      ["pi", "Pali"],
      ["pl", "Polish"],
      ["pt", "Portuguese"],
      ["ps", "Pushto"],
      ["qu", "Quechua"],
      ["rm", "Romansh"],
      ["ro", "Romanian"],
      ["rn", "Rundi"],
      ["ru", "Russian"],
      ["sg", "Sango"],
      ["sa", "Sanskrit"],
      ["si", "Sinhala"],
      ["sk", "Slovak"],
      ["sl", "Slovenian"],
      ["se", "NorthernSami"],
      ["sm", "Samoan"],
      ["sn", "Shona"],
      ["sd", "Sindhi"],
      ["so", "Somali"],
      ["st", "Sotho"],
      ["es", "Spanish"],
      ["sc", "Sardinian"],
      ["sr", "Serbian"],
      ["ss", "Swati"],
      ["su", "Sundanese"],
      ["sw", "Swahili"],
      ["sv", "Swedish"],
      ["ty", "Tahitian"],
      ["ta", "Tamil"],
      ["tt", "Tatar"],
      ["te", "Telugu"],
      ["tg", "Tajik"],
      ["tl", "Tagalog"],
      ["th", "Thai"],
      ["bo", "Tibetan"],
      ["ti", "Tigrinya"],
      ["to", "Tonga"],
      ["tn", "Tswana"],
      ["ts", "Tsonga"],
      ["tk", "Turkmen"],
      ["tr", "Turkish"],
      ["tw", "Twi"],
      ["ug", "Uighur"],
      ["uk", "Ukrainian"],
      ["ur", "Urdu"],
      ["uz", "Uzbek"],
      ["ve", "Venda"],
      ["vi", "Vietnamese"],
      ["vo", "Volapük"],
      ["cy", "Welsh"],
      ["wa", "Walloon"],
      ["wo", "Wolof"],
      ["xh", "Xhosa"],
      ["yi", "Yiddish"],
      ["yo", "Yoruba"],
      ["za", "Zhuang"],
      ["zu", "Zulu"]
    ].each do |(code, name)|
      Resource::Models::Language.find_or_create(code: code, name: name)
    end

    [
      ["CC","Attribution"],
      ["CC BY-ND", "Attribution-NoDerivs"],
      ["CC BY-NC-SA", "Attribution-NonCommercial-ShareAlike"],
      ["CC BY-SA", "Attribution-ShareAlike"],
      ["CC BY-NC", "Attribution-NonCommercial"],
      ["CC BY-NC-ND", "Attribution-NonCommercial-NoDerivs"]
    ].each do |(code, name)|
      Resource::Models::License.find_or_create(code: code, name: name)
    end
  end
end